# topic:
#  cmd_vel: cmd_vel #/coconut_vel
#  odom: odom

# service:
#  name: test

# frame:
#  odom: odom
#  base_footprint: base_footprint

topic:
 cmd_vel: /coconut_vel
 odom: /odom_gz

service:
 name: test

frame:
 odom: odom_gz
 base_footprint: base_footprint

apriltag:
 left:
  tag_id: 24
  frame_name: tag_24
 middle:
  tag_id: 25
  frame_name: tag_25
 right:
  tag_id: 26
  frame_name: tag_26
 

control:
 distance_goal_tolerance_first_predocking: 0.05 # [meters]linear //0.07
 distance_goal_tolerance_next_predocking: 0.0001 # [meters]linear //0.015
 distance_goal_tolerance_last_predocking: 0.006 # [meters] linear

 heading_error_threshold: 0.15 # [rad]// 0.2 // ปรับทิศทางหุ่นยนต์เมื่อทิศทางระหว่างหุ่นยนต์กับ pre-docking มีความคลาดเคลื่อนเกินกว่าที่กำหนด ก่อนที่หุ่นยนต์จะเคลื่อนที่ไปยังจุด pre-docking 
 
 # To prevent robots from adjusting heading unnecessarily
 yaw_adjust_disable_by_distance_x: 0.45 # [meters] // 0.4,0.3 //from apriltag // ไม่มีการปรับทิศทางหุ่นยนต์ระหว่างเคลื่อนที่ไปยัง pre-docking ใหม่ เมื่อหุ่นยนต์อยู่ใกล้กับ station ในระยะด้านหน้าน้อยกว่าที่กำหนดไว้ x เมตร 

 #PID
 kp_angular: 3.0 #angular //1.2
 kp_linear: 2.9 #linear //0.4
 heading_tolerance: 0.001 #angular [rad]
 yaw_goal_tolerance: 0.01 #angular [rad] ex. 0.005
 linear_velocity_max: 0.04 #linear [m/s] 0.04 //0.08
 angular_velocity_max: 0.35 #angular [m/s] 0.27 // 0.7 //0.65

 palabola_params:
  alpha: 0.1
  max_dist_to_deatect_all_tags: 2.0 # [meters] recommend


docking:
 delay_before_start: 1.0 # [sec]
 docking_distance: 0.39 #meters 0.32
 min_dist_to_deatect_all_tags: 0.49 # [meters] from base_footprint to tag, should more than docking_distance ex.0.3
 first_pre_docking_distance: 0.85 # [meters] //0.85 //0.8
 docking_direction: backward # can choose mode "forward" or "backward" , the camera must attach at choosed direction